### ISSUE TITLE
[MCA reborn] Possible mod compat issue

### ISSUE THREAD

**Issue by AbsolemJackdaw** [ArtixAllMighty/FatChickens#7]
### User states : 
````
Love this mod! Sadly I can't use it with MCA Reborn, it causes the villagers to not communicate with the player   
if this mod is installed.  When attempting to talk with MCA Reborn Villagers,   
their dialogue options won't appear at all, the only kind of GUI that shows up is if their employed villagers.  
Not sure why this is happening, but if it ever gets fixed I'll re-download this!
````

**Comment by SplendidAlakey** [comment]
I am now unable to interact with any entities at all, when this mod is installed. I'm not the same person, who reported the MCA issue. The issue was not present before, so it might have something to do with loader and API updates?

Logs without literally any other mods: https://gist.github.com/SplendidAlakey/1c70b40f6d543bab436a26ea010e5dd1. I don't see any errrors at all. Unable to enter boats, trade with wandering traders and villagers, mount animals, etc.

**Comment by TelepathicGrunt** [comment]
@AbsolemJackdaw 

https://github.com/AbsolemJackdaw/FatChickens/blob/338f65a7b179333ea17fbd9b3373a13bf2a32000/Fabric/src/main/java/jackdaw/fatchicken/events/FeedAnimalsEvent.java#L46

This needs to be PASS. Not FAIL my dude. FAIL will cancel the rest of the interactions. Breaks everyone. PASS says to continue to the next interaction event

**Comment by Sunconure11** [comment]
@AbsolemJackdaw 

I think this applies to vanilla villagers too.
